# Generated by Django 5.1.3 on 2025-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_model_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='OrderItem_Model',
        ),
    ]
