# Generated by Django 5.1.3 on 2025-01-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_model_status_delete_orderitem_model'),
        ('products', '0004_product_model_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order_model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
