# Generated by Django 5.1.3 on 2025-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_model_slug_alter_product_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
